#!/bin/bash

for f in ./R/*~; do
    rm -f $f
done

for f in ./R/*.ps; do
    rm -f $f
done


for f in ./man/*~; do
    rm -f $f
done

for f in ./man/*.ps; do
    rm -f $f
done

for f in ./inst/doc/*~; do
    rm -f $f
done

for f in ./inst/doc/party-*; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./tests/*.ps; do
    rm -f $f
done

for f in ./tests/*~; do
    rm -f $f
done

for f in ./src/*.*o; do
    rm -f $f
done

for f in ./src/*~; do
    rm -f $f
done

for f in ./demo/*~; do
    rm -f $f
done

for f in *~; do
    rm -f $f
done

rm -rf inst/documentation
rm -rf inst/documentation

find . -name "DEADJOE" -exec rm -f {} \;

exit 0
